# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:05
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
                ('with_links', django.db.models.manager.Manager()),
            ],
        ),
    ]
