# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 15:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20170425_1505'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='link',
            managers=[
                ('with_votes', django.db.models.manager.Manager()),
            ],
        ),
    ]
